export const DashboardColors = {
  background: '#000000',
  backgroundTop: '#0A1A3A',
  backgroundMid: '#061028',
  surface: '#141416',
  surfaceElevated: '#1C1C1E',
  surfaceMuted: '#252528',
  text: '#FFFFFF',
  textSecondary: '#A0A8B8',
  textMuted: '#6B7280',
  accent: '#5B9EFF',
  accentSoft: 'rgba(91, 158, 255, 0.16)',
  micro: '#34D399',
  microSoft: 'rgba(52, 211, 153, 0.16)',
  macro: '#FBBF24',
  macroSoft: 'rgba(251, 191, 36, 0.16)',
  danger: '#FF453A',
  dangerSoft: 'rgba(255, 69, 58, 0.16)',
  border: 'rgba(255, 255, 255, 0.08)',
  chartTrack: 'rgba(255, 255, 255, 0.08)',
} as const;

export type BillingCycle = 'weekly' | 'monthly' | 'yearly';
export type SpendScale = 'micro' | 'macro';

export type SubscriptionStatus = 'active' | 'cancelled';

export type Subscription = {
  id: string;
  name: string;
  amount: number;
  currency: string;
  billingCycle: BillingCycle;
  category: string;
  scale: SpendScale;
  nextBillingDate: string;
  color: string;
  icon: string;
  providerKey?: string;
  status?: SubscriptionStatus;
  isTrial?: boolean;
  trialEndsInDays?: number;
  unusedDays?: number;
  /** Optimistic concurrency version from the API */
  version?: number;
};

export const SUBSCRIPTION_CATEGORIES = [
  'All',
  'Entertainment',
  'Productivity',
  'Cloud',
  'Health',
  'News',
  'Shopping',
] as const;

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'Netflix',
    amount: 15.49,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Entertainment',
    scale: 'micro',
    nextBillingDate: '2026-09-12',
    color: '#E50914',
    icon: 'N',
    providerKey: 'netflix',
    status: 'active',
  },
  {
    id: '2',
    name: 'Spotify',
    amount: 10.99,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Entertainment',
    scale: 'micro',
    nextBillingDate: '2026-09-08',
    color: '#1DB954',
    icon: '♪',
    providerKey: 'spotify',
    status: 'active',
  },
  {
    id: '3',
    name: 'Adobe Creative Cloud',
    amount: 59.99,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Productivity',
    scale: 'macro',
    nextBillingDate: '2026-09-18',
    color: '#FF0000',
    icon: 'Ae',
    providerKey: 'adobe',
    status: 'active',
  },
  {
    id: '4',
    name: 'iCloud+',
    amount: 2.99,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Cloud',
    scale: 'micro',
    nextBillingDate: '2026-09-22',
    color: '#3B82F6',
    icon: '☁',
    providerKey: 'icloud',
    status: 'active',
  },
  {
    id: '5',
    name: 'ChatGPT Plus',
    amount: 20,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Productivity',
    scale: 'macro',
    nextBillingDate: '2026-09-14',
    color: '#10A37F',
    icon: '✦',
    providerKey: 'openai',
    status: 'active',
    isTrial: true,
    trialEndsInDays: 3,
  },
  {
    id: '6',
    name: 'YouTube Premium',
    amount: 13.99,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Entertainment',
    scale: 'micro',
    nextBillingDate: '2026-09-25',
    color: '#FF0000',
    icon: '▶',
    providerKey: 'youtube',
    status: 'active',
    unusedDays: 47,
  },
  {
    id: '7',
    name: 'Notion',
    amount: 96,
    currency: 'USD',
    billingCycle: 'yearly',
    category: 'Productivity',
    scale: 'micro',
    nextBillingDate: '2026-10-02',
    color: '#111111',
    icon: 'N',
    providerKey: 'notion',
    status: 'active',
  },
  {
    id: '8',
    name: 'AWS',
    amount: 84.2,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Cloud',
    scale: 'macro',
    nextBillingDate: '2026-09-07',
    color: '#FF9900',
    icon: '☁',
    providerKey: 'aws',
    status: 'active',
  },
  {
    id: '9',
    name: 'Headspace',
    amount: 69.99,
    currency: 'USD',
    billingCycle: 'yearly',
    category: 'Health',
    scale: 'micro',
    nextBillingDate: '2026-09-30',
    color: '#F47D31',
    icon: '◉',
    providerKey: 'headspace',
    status: 'active',
    isTrial: true,
    trialEndsInDays: 1,
  },
  {
    id: '10',
    name: 'The Athletic',
    amount: 7.99,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'News',
    scale: 'micro',
    nextBillingDate: '2026-09-19',
    color: '#111111',
    icon: 'A',
    providerKey: 'athletic',
    status: 'active',
    unusedDays: 62,
  },
  {
    id: '11',
    name: 'Amazon Prime',
    amount: 139,
    currency: 'USD',
    billingCycle: 'yearly',
    category: 'Shopping',
    scale: 'macro',
    nextBillingDate: '2026-11-05',
    color: '#FF9900',
    icon: 'a',
    providerKey: 'prime',
    status: 'active',
  },
  {
    id: '12',
    name: 'Figma Pro',
    amount: 15,
    currency: 'USD',
    billingCycle: 'monthly',
    category: 'Productivity',
    scale: 'micro',
    nextBillingDate: '2026-09-16',
    color: '#A259FF',
    icon: 'F',
    providerKey: 'figma',
    status: 'active',
    isTrial: true,
    trialEndsInDays: 5,
  },
];
